### ISSUE TITLE
Infografía de Hilos

### ISSUE THREAD

**Issue by Abraham890** [SistemasTecTlaxiaco/infografia-de-hilos-Abraham890#2]
[Abraham_Reyes_Ortiz_Infografia_de_Hilos.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Abraham890/files/6466595/Abraham_Reyes_Ortiz_Infografia_de_Hilos.pdf)

**Comment by Eva155** [comment]
20 PUNTOS 
CALIFICÓ: EVA AGUILAR AVENDAÑO

**Comment by josealfredo79** [comment]
Bien hecho y revisado
